version: '3'

services:
  web:
    build:
      context: .
      dockerfile: server/nginx/Dockerfile
    ports:
      - "8055:80"
    volumes:
      - ./server/app/:/var/www
      - ./server/nginx/conf.d:/etc/nginx/conf.d
    container_name: project_web
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: server/app/Dockerfile
    env_file:
      - .env
    volumes:
      - ./server/app/:/var/www
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgresql}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_DATABASE:-postgresql}